export interface TemplateDef {
  id: number;
  name: string;
  marathiName: string;
  themeColor: string; // Hex color for primary background
  secondaryColor: string;
  accentGold: string;
  textColor: string;
  headerBlessing: string;
  mainGreeting: string;
  subGreeting: string;
  footerStyle: 'royal-card' | 'gold-ribbon' | 'classic-frame' | 'modern-dark' | 'silk-banner';
  badgeText: string;
  symbol: 'modak' | 'diya' | 'crown' | 'lotus' | 'tootari' | 'sun';
}

export const TEMPLATE_DEFS: TemplateDef[] = [
  {
    id: 1,
    name: 'Royal Velvet Red & Gold',
    marathiName: 'शाही लाल-सुवर्ण',
    themeColor: '#7A0C16',
    secondaryColor: '#B81423',
    accentGold: '#FFD700',
    textColor: '#FFFFFF',
    headerBlessing: '॥ श्री गणेशाय नमः ॥',
    mainGreeting: 'गणेशोत्सवाच्या हार्दिक शुभेच्छा',
    subGreeting: 'मंगलमूर्ती बाप्पाच्या कृपेने आपल्या आयुष्यात सुख, समृद्धी आणि आरोग्य लाभो!',
    footerStyle: 'royal-card',
    badgeText: 'हार्दिक शुभेच्छा',
    symbol: 'modak',
  },
  {
    id: 2,
    name: 'Saffron Golden Sun',
    marathiName: 'केसरी सुवर्ण प्रभा',
    themeColor: '#C44100',
    secondaryColor: '#E65C00',
    accentGold: '#FFDF6D',
    textColor: '#FFFFFF',
    headerBlessing: '॥ वक्रतुण्ड महाकाय सूर्यकोटि समप्रभ ॥',
    mainGreeting: 'श्री गणेश चतुर्थीच्या मनःपूर्वक शुभेच्छा',
    subGreeting: 'विघ्नहर्ता गणपती बाप्पा आपल्या सर्व अडचणी दूर करो हीच प्रार्थना!',
    footerStyle: 'gold-ribbon',
    badgeText: 'गणपती बाप्पा मोरया',
    symbol: 'sun',
  },
  {
    id: 3,
    name: 'Siddhivinayak Palace',
    marathiName: 'सिद्धिविनायक राज दरबार',
    themeColor: '#4A0404',
    secondaryColor: '#8B0000',
    accentGold: '#F3E5AB',
    textColor: '#FFFFFF',
    headerBlessing: '॥ सर्वविघ्नहर्त्रे नमः ॥',
    mainGreeting: 'गणेशोत्सव पर्वाच्या अनंत शुभेच्छा',
    subGreeting: 'सुखकर्ता दुखहर्ता श्री गजानन आपल्या घरी आनंदाचा वर्षाव करो!',
    footerStyle: 'classic-frame',
    badgeText: 'शुभ गणेशोत्सव',
    symbol: 'crown',
  },
  {
    id: 4,
    name: 'Royal Midnight Gold Dust',
    marathiName: 'शाही निळा सुवर्ण',
    themeColor: '#0F1C3F',
    secondaryColor: '#1A2B56',
    accentGold: '#F8CE46',
    textColor: '#FFFFFF',
    headerBlessing: '॥ ॐ गं गणपतये नमः ॥',
    mainGreeting: 'अष्टविनायक कृपाप्रसाद',
    subGreeting: 'बाप्पाच्या आगमनाने परिसर उजळून निघो, सुखाची नवी पहाट येवो!',
    footerStyle: 'modern-dark',
    badgeText: 'विघ्नहर्त्याचे आगमन',
    symbol: 'lotus',
  },
  {
    id: 5,
    name: 'Marathmola Heritage Orange',
    marathiName: 'मराठमोळा पारंपारिक',
    themeColor: '#8C1D03',
    secondaryColor: '#D9381E',
    accentGold: '#FFC837',
    textColor: '#FFFFFF',
    headerBlessing: '॥ एकदन्ताय विद्महे वक्रतुण्डाय धीमहि ॥',
    mainGreeting: 'आनंदमय गणेशोत्सव',
    subGreeting: 'पारंपारिक उत्साहात साजरी करूया विघ्नहर्त्याची भक्तिमय पूजा!',
    footerStyle: 'silk-banner',
    badgeText: 'उत्सव आनंदाचा',
    symbol: 'tootari',
  },
  {
    id: 6,
    name: 'Golden Shrine & Diyas',
    marathiName: 'सुवर्ण दीपम उत्सव',
    themeColor: '#5C1D00',
    secondaryColor: '#A03000',
    accentGold: '#FFE57F',
    textColor: '#FFFFFF',
    headerBlessing: '॥ सिद्धिबुद्धिसहिताय श्रीमन्महागणाधिपतये नमः ॥',
    mainGreeting: 'मंगलमय गणेश चतुर्थी',
    subGreeting: 'दीपोत्सवाच्या दीप्तीने आणि बाप्पाच्या प्रेमाने जीवन उजळू दे!',
    footerStyle: 'royal-card',
    badgeText: 'दीप्त गणेशोत्सव',
    symbol: 'diya',
  },
  {
    id: 7,
    name: 'Royal Silk Maroon',
    marathiName: 'रेशमी मरून राजेशाही',
    themeColor: '#540813',
    secondaryColor: '#800C1D',
    accentGold: '#FFD700',
    textColor: '#FFFFFF',
    headerBlessing: '॥ चिंतामणी प्रसन्न ॥',
    mainGreeting: 'चिंतामणी चरणी नतमस्तक',
    subGreeting: 'सर्व मनोकामना पूर्ण होवोत, घराघरात सुख शांततेचा वास राहो!',
    footerStyle: 'gold-ribbon',
    badgeText: 'मंगलमूर्ती मोरया',
    symbol: 'modak',
  },
  {
    id: 8,
    name: 'Royal Gold Rangoli',
    marathiName: 'सुवर्ण रांगोळी वैभव',
    themeColor: '#6B1100',
    secondaryColor: '#9C1A00',
    accentGold: '#FFDF00',
    textColor: '#FFFFFF',
    headerBlessing: '॥ श्री गजानन प्रसन्न ॥',
    mainGreeting: 'गणेशोत्सवानिमित्त मंगलमय शुभेच्छा',
    subGreeting: 'बुद्धीचा दाता श्री गणेश तुम्हा सर्वांना उदंड यश आणि प्रगती देवो!',
    footerStyle: 'classic-frame',
    badgeText: 'वैभवशाली गणेशोत्सव',
    symbol: 'lotus',
  },
  {
    id: 9,
    name: 'Majestic Saffron Silk',
    marathiName: 'वैभवशाली केसरी रेशीम',
    themeColor: '#B32B00',
    secondaryColor: '#E63900',
    accentGold: '#FFE082',
    textColor: '#FFFFFF',
    headerBlessing: '॥ प्रथम पूज्य श्री गणेश ॥',
    mainGreeting: 'भाद्रपद गणेशोत्सव पर्व',
    subGreeting: 'मोरयाच्या नामात तल्लीन होऊन साजरा करूया हा पवित्र उत्सव!',
    footerStyle: 'silk-banner',
    badgeText: 'बाप्पा मोरया',
    symbol: 'tootari',
  },
  {
    id: 10,
    name: 'Royal Purple Velvet',
    marathiName: 'शाही जांभळा सुवर्ण',
    themeColor: '#380B4A',
    secondaryColor: '#561470',
    accentGold: '#F5D061',
    textColor: '#FFFFFF',
    headerBlessing: '॥ विघ्नेश्वराय वरदाय सुरप्रियाय ॥',
    mainGreeting: 'श्री गणेशाचा दिव्य आशीर्वाद',
    subGreeting: 'तुमच्या आयुष्यातील सर्व संकटांचे हरण होवो, बाप्पाचा वरदहस्त लाभो!',
    footerStyle: 'modern-dark',
    badgeText: 'वरदविनायक कृपा',
    symbol: 'crown',
  },
  {
    id: 11,
    name: 'Golden Festive Festoon',
    marathiName: 'सुवर्ण तोरण उत्सव',
    themeColor: '#850014',
    secondaryColor: '#B3001B',
    accentGold: '#FFD700',
    textColor: '#FFFFFF',
    headerBlessing: '॥ मोरया मोरया मी बाळ ताकते ॥',
    mainGreeting: 'गणपती बाप्पा मोरया, पुढच्या वर्षी लवकर या!',
    subGreeting: 'हर्ष आणि उल्हासाने नटलेला हा गणेशोत्सव तुम्हा सर्वांना समृद्धीचा जावो!',
    footerStyle: 'royal-card',
    badgeText: 'मंगलमूर्ती मोरया',
    symbol: 'modak',
  },
];
